name: Eruption
author: Roxo
version: '${project.version}'
api-version: 1.17
main: me.roxo.eruption.Eruption
depend: [ProjectKorra]
eruption.player:
  default: true
  children:
    bending.ability.Eruption: true